openapi: 3.1.0
x-stoplight:
  id: 3lghmwqbc6uha
info:
  title: Church Sync Openapi
  version: '1.0'
  description: Church Sync Openapi
  contact:
    name: Nana Kwesi Ofosu-Aikins
    email: nanaaikinson24@gmail.com
    url: nanaaikinson.com
servers:
  - url: 'https://churchsync.test/api'
    description: Local
tags:
  - name: admin
  - name: central
  - name: mobile
  - name: tenant
paths:
  /c/auth/social/sign-up:
    post:
      summary: Your GET endpoint
      tags:
        - central
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialSignUpResponse'
      operationId: auth-social-sign-up
      description: 'Central: auth social sign up'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
              required:
                - accessToken
components:
  schemas:
    SocialSignUpResponse:
      type: object
      x-examples:
        Example 1:
          data:
            user:
              firstName: Nana Kwesi
              lastName: Ofosu-Aikins
              avatar: 'https://lh3.googleusercontent.com/a/AAcHTtdJkVwMUPqn-uF54RS_MRQZSJvS5TRj588XlviOCpDo=s96-c'
            tokens:
              accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Noc3luYy50ZXN0L2FwaS9jL2F1dGgvc29jaWFsL3NpZ24tdXAiLCJpYXQiOjE2OTMzMTY5ODUsImV4cCI6MTY5MzMyMDU4NSwibmJmIjoxNjkzMzE2OTg1LCJqdGkiOiJKTm1IZ2c4MDlhZENlOXBIIiwic3ViIjoiMDFIOTBSWENTVzFOMjJESzE2R0VERzE0M1IiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiY2hhbm5lbCI6InRlbmFudCIsIm9uYm9hcmRpbmdfc3RlcCI6InRlbmFudCBvbmJvYXJkaW5nIn0.Mp59SQkJpKIOkRgiWV93u0k_T-GobzaWvEGwsVKi8cE
              expiresAt: '2023-08-30T13:49:45.665606Z'
              refreshToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Noc3luYy50ZXN0L2FwaS9jL2F1dGgvc29jaWFsL3NpZ24tdXAiLCJpYXQiOjE2OTMzMTY5ODUsImV4cCI6MTY5MzMyMDU4NSwibmJmIjoxNjkzMzE2OTg1LCJqdGkiOiJlU0hLREx0S3NlYTVDejBvIiwic3ViIjoiMDFIOTBSWENTVzFOMjJESzE2R0VERzE0M1IiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiY2hhbm5lbCI6InRlbmFudCIsIm9uYm9hcmRpbmdfc3RlcCI6InRlbmFudCBvbmJvYXJkaW5nIn0.GECZ6C57ycJL0KqXHCvIJGv27OQGcihY5tbuiPKYH3k
          message: ''
      properties:
        data:
          type: object
          required:
            - user
            - tokens
          properties:
            user:
              type: object
              required:
                - firstName
                - lastName
                - avatar
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                avatar:
                  type: string
            tokens:
              type: object
              required:
                - accessToken
                - expiresAt
                - refreshToken
              properties:
                accessToken:
                  type: string
                expiresAt:
                  type: string
                refreshToken:
                  type: string
        message:
          type: string
      required:
        - data
        - message
      description: Google sign up response
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
