openapi: 3.1.0
x-stoplight:
  id: 3lghmwqbc6uha
info:
  title: Church Sync Openapi
  version: '1.0'
  description: Church Sync Openapi
  contact:
    name: Nana Kwesi Ofosu-Aikins
    email: nanaaikinson24@gmail.com
    url: nanaaikinson.com
servers:
  - url: 'https://churchsync.test/api'
    description: Local
tags:
  - name: admin
  - name: central
  - name: mobile
  - name: tenant
paths:
  /c/auth/social/sign-up:
    post:
      summary: Your GET endpoint
      tags:
        - central
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthUserResposne'
      operationId: auth-social-sign-up
      description: 'Central: auth social sign up'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
              required:
                - accessToken
  /c/auth/local/sign-up:
    post:
      summary: Your GET endpoint
      tags:
        - central
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthUserResposne'
      operationId: auth-local-sign-up
      description: 'Central: auth local sign up'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  firstName: Nana
                  lastName: Aikinson
                  email: nanaaikinson2020@gmail.com
                  password: Pa$$w0rd
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - password
  /c/organization/onboard:
    post:
      summary: Your GET endpoint
      tags:
        - central
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
      operationId: organization-onboarding
      description: 'Central: Organzation onboarding'
      parameters: []
      security:
        - JWT: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OnboardingRequest'
    parameters: []
components:
  schemas:
    OnboardingRequest:
      type: object
      x-examples:
        Example 1:
          name: ''
          roleAtChurch: ''
          defaultBranch: ''
          phoneNumber: ''
          location: ''
          logo: ''
      properties:
        name:
          type: string
        roleAtChurch:
          type: string
        defaultBranch:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        logo:
          type:
            - string
            - 'null'
          format: binary
      required:
        - name
        - roleAtChurch
        - defaultBranch
        - phoneNumber
        - location
      x-stoplight:
        id: 3a96f6c69399b
      title: OnboardingRequest
      description: ''
    MessageResponse:
      title: MessageResponse
      x-stoplight:
        id: bnx29eprw94jt
      type: object
      properties:
        message:
          type: string
      required:
        - message
    AuthUserResposne:
      type: object
      x-examples:
        Example 1:
          data:
            user:
              firstName: Nana
              lastName: Aikinson
              email: nanaaikinson2020@gmail.com
              avatar: null
              onboardingStep: account verification
              organizations: []
            token:
              accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Noc3luYy50ZXN0L2FwaS9jL2F1dGgvbG9jYWwvc2lnbi11cCIsImlhdCI6MTY5MzM1NjMyOCwiZXhwIjoxNjkzMzYzNTI4LCJuYmYiOjE2OTMzNTYzMjgsImp0aSI6Imh6ZGhvbU5XeTNQQWI3VzIiLCJzdWIiOiIwMUg5MVlFMVE5R1FEMEgxNEdYUFo5UFJTRiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJjaGFubmVsIjoidGVuYW50In0.fMGScLG9qDsYbSUManZnhmHQ5tLhsd_NiXkstRb5DUs
              expiresAt: '2023-08-31T00:45:28.689725Z'
              refreshToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Noc3luYy50ZXN0L2FwaS9jL2F1dGgvbG9jYWwvc2lnbi11cCIsImlhdCI6MTY5MzM1NjMyOCwiZXhwIjoxNjkzNDQyNzI4LCJuYmYiOjE2OTMzNTYzMjgsImp0aSI6IlczTmdOVE9rMUlra0NISDIiLCJzdWIiOiIwMUg5MVlFMVE5R1FEMEgxNEdYUFo5UFJTRiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJjaGFubmVsIjoidGVuYW50In0.H5do1rZpoWDd5AX--4BjA3cH366XEWVY3V2Sr0Z3lek
          message: |-
            Thank you for signing up! We're thrilled to have you join Church Sync.
                    Your account creation is almost complete. Please check your email for a verification code.
                    Once you've received it, simply enter the code in the verification code input to finalize your account setup.
                    We can't wait to see you make the most of our platform!
      x-stoplight:
        id: 3cf8a7923c54b
      properties:
        data:
          type: object
          required:
            - user
          properties:
            user:
              type: object
              required:
                - firstName
                - lastName
                - email
                - avatar
                - onboardingStep
                - organizations
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                avatar:
                  type:
                    - string
                    - 'null'
                onboardingStep:
                  type: string
                organizations:
                  type: array
                  items:
                    type: object
            token:
              type: object
              required:
                - accessToken
                - expiresAt
              properties:
                accessToken:
                  type: string
                expiresAt:
                  type: string
                refreshToken:
                  type: string
        message:
          type: string
      required:
        - data
        - message
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
